### ISSUE TITLE
Brackets in action

### ISSUE THREAD

**Issue by kafejo** [apiaryio/apiblueprint.org#31]
Let's assume endpoint and action

```
## Avatar [/me/avatar]
### New (update) avatar [POST]
```
this won't show in rendered documentation unless we remove the brackets. 
```
## Avatar [/me/avatar]
### New update avatar [POST]
```
Sorry if that is a wrong repository to file an issue of that kind.

**Comment by kylef** [comment]
As per the API Blueprint specification, an [identifier](https://apiblueprint.org/documentation/specification.html#def-identifier) such as that used in the [action](https://apiblueprint.org/documentation/specification.html#def-action-section) may not contain brackets so this is intended.

> A section definition **may** or **must** include an identifier of the section. An **identifier is any non-empty combination of any character except `[`, `]`, `(`, `)` and newline characters**.
