### ISSUE TITLE
Enable CORS for api.apiblueprint.org

### ISSUE THREAD

**Issue by JackuB** [apiaryio/apiblueprint.org#38]
Pretty please?

**Comment by kylef** [comment]
@JackuB Can you please elaborate with more description?

**Comment by JackuB** [comment]
Wanted to use parsing service from a browser, but missing CORS prevents it

<img width="1176" alt="snimek obrazovky 2016-03-29 v 18 22 24" src="https://cloud.githubusercontent.com/assets/1788727/14115436/47bc8a86-f5db-11e5-8964-c258fd97cae5.png">

**Comment by kylef** [comment]
@JackuB Thanks, let me take a look into this and get back to you.

**Comment by pksunkara** [comment]
This is done.
