### ISSUE TITLE
URL parameters added as query string parameters

### ISSUE THREAD

**Issue by togglebrain** [apiaryio/apiblueprint.org#55]
In a sample API, I have an endpoint as:
![def](https://cloud.githubusercontent.com/assets/14012589/17731639/af5336da-648b-11e6-9ae4-26a8be02c62f.png)

The console opened for the first time shows the following URL:
http://private-7775c-testblueprint4.apiary-mock.com/questions/id

However, on specifying a value of Id under URL parameters,  the URL changes to:
http://private-7775c-testblueprint4.apiary-mock.com/questions/234?id=234

The Id is appended twice as shown, which sends an incorrect request.

![2016-08-17 15_01_12-testblueprint apiary](https://cloud.githubusercontent.com/assets/14012589/17731575/7a863af6-648b-11e6-9d12-9c10b545c70d.png)

**Comment by zdne** [comment]
@togglebrain this seems like a bug on our side. I've reported it in our (Apiary) internal bug tracking system and we will fix it as soon as possible! Thanks for your report!

**Comment by kylef** [comment]
<img width="1135" alt="screen shot 2016-11-21 at 16 04 13" src="https://cloud.githubusercontent.com/assets/44164/20489926/2fcdfc1e-b004-11e6-8ca2-a7a90bfaae44.png">

Just want to update this issue, the problem has been resolved now. If you are still having any problems here please reach out to Apiary support (support@apiary.io).
