### ISSUE TITLE
Tools section broken

### ISSUE THREAD

**Issue by Ullaakut** [apiaryio/apiblueprint.org#59]
![screen shot 2016-09-19 at 09 11 45](https://cloud.githubusercontent.com/assets/6976628/18624574/20f3aaa0-7e49-11e6-899b-91efde69f187.png)

The tools section worked just fine last week, but now it does not contain any tags except `Tools` and doesn't contain any tool.

This bug has been reproduced under Chrome OSX as well as Firefox Ubuntu.

Could it be because of a format error here : 

`tools.yaml`

```json

name: doc-proxy
  summary: Node server to generate documentation.md file for all the endpoints supported by your server
  url: https://github.com/sandeep89/doc-proxy
  tags:[]

```

There is no space between the `tags` variable and its value.

**Comment by kylef** [comment]
Thanks for reporting this @Ullaakut, I've fixed this in https://github.com/apiaryio/apiblueprint.org/issues/60 and also added a CI step to parse the YAML document so we can prevent this in the future.
